language: csharp
solution: ./src/library.net.sln
env:
 matrix:
  - MONO_VERSION="3.8.0"
install:
 - nuget restore ./src/library.net.sln
script:
 - xbuild /p:Configuration=Release ./src/library.net.sln